### ISSUE TITLE
How to change the column header style.Please guide me

### ISSUE THREAD

**Issue by wipmuralikrishnank24** [hjalmers/angular-generic-table#102]
How to change the column header style.Please guide me

**Comment by hjalmers** [comment]
Could you be a bit more specific about what you're trying to do perhaps? It's just a normal table in the end so if you're just referring to css styling you style it using normal css, e.g. 

```css
table thead tr th {
  background: red;
}
```
